version: "2"

services:

        web:
                build: ./dockerfile_apache
                ports:
                   - "8082:80"
                volumes:
                   - ./html/:/var/www/html
                   - ../../piccean_images:/var/www/html/images

        mysql:
                build: ./dockerfile_mysql
                ports:
                   - "33060:3306"
                environment:
                   MYSQL_ROOT_PASSWORD: root
                volumes_from:
                   - data

        phpmyadmin:
                image: phpmyadmin/phpmyadmin
                environment:
                   - PMA_ARBITRARY=1
                   - PMA_HOST=mysql
                   - PMA_USER=root
                   - PMA_PASSWORD=root
                links:
                   - mysql
                ports:
                   - "8083:80"
                volumes:
                   - "../../phpmyadmin/sessions:/sessions"

        httpd:
                build: ./dockerfile_httpd

        data:
                image: busybox:1
                volumes:
                   - ../../piccean_db/mysql/data:/var/lib/mysql
